# apiVersion: v1
# kind: Pod 
# metadata:
#   name: myapp-pod
# spec:
#   containers: 
#    - name: mycon
#      image: nginx
#      ports: 
#       - containerPort: 80 
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
    - name: mycon
      image: nginx
      ports:
        - containerPort: 80