apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: myapp   # Pod ka label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30011  # 30000–32767 range
  type: NodePort
